### ISSUE TITLE
Pages non responsives

### ISSUE THREAD

**Issue by nicolasterral** [mauquie/ailipse#1]
De nombreuses pages ne sont pas responsive, limitant les actions de l'utilisateur ou impactant négativement l'ergonomie.

Pages d'inscription & connexion
---
- Le bouton d'inscription de la page d'inscription n'est pas accessible sur certaines résolutions
- Le bouton de connexion de la page de connexion n'est pas accessible sur certaines résolutions

Page visualisation des annonces
---
- La page de visualisation des annonces n'est pas responsive : carte coupée, listes déroulantes qui se chevauchent

Page modélisation 3D
---
- Les éléments de la page modélisation 3D se chevauchent selon le niveau de zoom / la résolution ("couleur de fond", "voile constructeur", "votre voile", "Echelle différence").
- La liste déroulante des contrôles de la page modélisation 3D affiche des urls
- Le panel des mesures de la page modélisation 3D est sur une couche inférieure à l'échelle, ce qui nuit à la lisibilité.

**Comment by Squid7331** [comment]
Problèmes résolus.

**Comment by julien-terral** [comment]
Problèmes résolus.
