### ISSUE TITLE
Panel d'administration

### ISSUE THREAD

**Issue by nicolasterral** [mauquie/ailipse#2]
Anomalies rencontrées sur le panel d'administration
---
- Le panel d'administration est accessible à tous les membres à partir du menu de notifications.
- L'activation de comptes ou d'annonces n'est pas fonctionnelle (du moins avec un compte classique) et n'affiche pas de message d'erreur si l'action à échoué
- Il est possible d'avoir la case "tout cocher" de la liste des annonces/comptes de cochée sans que les cases d'en dessous ne le soient (problème d'ergonomie cf. comportement gmail). Pour reproduire : utiliser le bouton "tout cocher" puis décocher toutes les annonces. La case "tout cocher" reste active alors qu'elle ne devrait plus l'être

**Comment by julien-terral** [comment]
Problèmes résolus.
